# Generated by Django 2.2.4 on 2019-12-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='city',
        ),
        migrations.RemoveField(
            model_name='users',
            name='clas',
        ),
        migrations.AddField(
            model_name='users',
            name='password1',
            field=models.CharField(default='1234jyoti', max_length=20),
        ),
    ]
