# Generated by Django 2.2.4 on 2019-12-24 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191224_1305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
