# Generated by Django 2.2.4 on 2019-12-28 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Profile Summary',
                'verbose_name_plural': 'Profiles Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.profile',),
        ),
    ]
