# Generated by Django 2.2.4 on 2019-12-30 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
