# Generated by Django 2.2.4 on 2019-12-30 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='getphno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mob', models.IntegerField()),
                ('ver_code', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='getname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=1)),
                ('helpp', models.CharField(max_length=300)),
                ('clas', models.CharField(max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
