# Generated by Django 2.2.4 on 2019-12-30 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_getname_getphno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='getphno',
        ),
    ]
