# Generated by Django 2.2.4 on 2019-12-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_getphno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getphno',
            name='mob',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='getphno',
            name='ver_code',
            field=models.CharField(max_length=10),
        ),
    ]
