# Generated by Django 2.2.4 on 2019-12-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20191230_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='helpp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='getphno',
            name='user',
        ),
        migrations.DeleteModel(
            name='getname',
        ),
        migrations.DeleteModel(
            name='getphno',
        ),
    ]
