# Generated by Django 2.2.4 on 2019-12-30 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0015_auto_20191230_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='getphno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mobile_Number', models.CharField(max_length=10)),
                ('Verification_Code', models.CharField(max_length=10)),
                ('City', models.CharField(max_length=200)),
                ('I_am_a', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.status')),
                ('User_Name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='getname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('My_Name_is', models.CharField(max_length=200)),
                ('My_Gender', models.CharField(max_length=1)),
                ('I_Study_in_Class', models.CharField(max_length=2)),
                ('I_need_Help_with', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.helpp')),
                ('User_Name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
