# Generated by Django 2.2.4 on 2019-12-30 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_getname_getphno'),
    ]

    operations = [
        migrations.CreateModel(
            name='gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='getname',
            name='My_Gender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.gender'),
        ),
    ]
