# Generated by Django 2.2.4 on 2020-01-02 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20191230_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getname',
            name='My_Gender',
        ),
        migrations.DeleteModel(
            name='gender',
        ),
    ]
