# Generated by Django 2.2.4 on 2020-01-07 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200102_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getphno',
            name='I_am_a',
        ),
        migrations.RemoveField(
            model_name='getphno',
            name='User_Name',
        ),
        migrations.DeleteModel(
            name='getname',
        ),
        migrations.DeleteModel(
            name='getphno',
        ),
        migrations.DeleteModel(
            name='helpp',
        ),
        migrations.DeleteModel(
            name='status',
        ),
    ]
