# Generated by Django 2.2.4 on 2020-01-26 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0020_getname_getphno_helpp_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mobile_Number', models.CharField(max_length=10)),
                ('Verification_Code', models.CharField(max_length=10)),
                ('City', models.CharField(max_length=200)),
                ('User_Name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='getphno',
        ),
    ]
