# Generated by Django 2.2.4 on 2020-02-09 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='text',
        ),
    ]
