# Generated by Django 2.2.4 on 2020-02-15 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='msg',
            new_name='Enter_your_Query_Here',
        ),
        migrations.AddField(
            model_name='chat',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
