# Generated by Django 2.2.4 on 2019-12-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_auto_20191211_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('text1', models.TextField()),
                ('text2', models.TextField()),
            ],
        ),
    ]
