# Generated by Django 2.2.4 on 2019-12-21 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_intro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='intro',
        ),
    ]
