# Generated by Django 2.2.4 on 2019-12-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_delete_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='AQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('choice_one', models.CharField(max_length=200)),
                ('choice_two', models.CharField(max_length=200)),
                ('choice_three', models.CharField(max_length=200)),
                ('choice_four', models.CharField(max_length=200)),
                ('qtype', models.CharField(max_length=300)),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('choice_one', models.CharField(max_length=200)),
                ('choice_two', models.CharField(max_length=200)),
                ('choice_three', models.CharField(max_length=200)),
                ('choice_four', models.CharField(max_length=200)),
                ('qtype', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='IQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('choice_one', models.CharField(max_length=200)),
                ('choice_two', models.CharField(max_length=200)),
                ('choice_three', models.CharField(max_length=200)),
                ('choice_four', models.CharField(max_length=200)),
                ('qtype', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='OQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('choice_one', models.CharField(max_length=200)),
                ('choice_two', models.CharField(max_length=200)),
                ('choice_three', models.CharField(max_length=200)),
                ('choice_four', models.CharField(max_length=200)),
                ('qtype', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('choice_one', models.CharField(max_length=200)),
                ('choice_two', models.CharField(max_length=200)),
                ('choice_three', models.CharField(max_length=200)),
                ('choice_four', models.CharField(max_length=200)),
                ('qtype', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
