# Generated by Django 2.2.4 on 2020-01-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0008_aresult_eresult_iresult_oresult_presult'),
    ]

    operations = [
        migrations.AddField(
            model_name='aresult',
            name='Aptitude_1_desc',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='aresult',
            name='Aptitude_2_desc',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='eresult',
            name='Emotional_1_desc',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='eresult',
            name='Emotional_2_desc',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='iresult',
            name='Interest_1_desc',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='iresult',
            name='Interest_2_desc',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='oresult',
            name='Orientation_1_desc',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='oresult',
            name='Orientation_2_desc',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='presult',
            name='Personality_1_desc',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='presult',
            name='Personality_2_desc',
            field=models.TextField(default=None),
        ),
    ]
