# Generated by Django 2.2.4 on 2020-01-24 09:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Quiz', '0009_auto_20200114_1206'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AQuiz',
            new_name='CareerQuiz',
        ),
        migrations.RenameModel(
            old_name='EResult',
            new_name='Result',
        ),
        migrations.RemoveField(
            model_name='aresult',
            name='User_Name',
        ),
        migrations.DeleteModel(
            name='EQuiz',
        ),
        migrations.DeleteModel(
            name='IQuiz',
        ),
        migrations.RemoveField(
            model_name='iresult',
            name='User_Name',
        ),
        migrations.DeleteModel(
            name='OQuiz',
        ),
        migrations.RemoveField(
            model_name='oresult',
            name='User_Name',
        ),
        migrations.DeleteModel(
            name='PQuiz',
        ),
        migrations.RemoveField(
            model_name='presult',
            name='User_Name',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='Emotional_1',
            new_name='Interest_1',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='Emotional_1_desc',
            new_name='Interest_1_desc',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='Emotional_2',
            new_name='Interest_2',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='Emotional_2_desc',
            new_name='Interest_2_desc',
        ),
        migrations.DeleteModel(
            name='AResult',
        ),
        migrations.DeleteModel(
            name='IResult',
        ),
        migrations.DeleteModel(
            name='OResult',
        ),
        migrations.DeleteModel(
            name='PResult',
        ),
    ]
