# Generated by Django 2.2.4 on 2020-01-26 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Quiz', '0010_auto_20200124_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('choice_one', models.CharField(max_length=200)),
                ('choice_two', models.CharField(max_length=200)),
                ('choice_three', models.CharField(max_length=200)),
                ('choice_four', models.CharField(max_length=200)),
                ('qtype', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Interest_1', models.CharField(max_length=100)),
                ('Interest_1_desc', models.TextField(default=None)),
                ('Interest_2', models.CharField(max_length=100)),
                ('Interest_2_desc', models.TextField(default=None)),
                ('User_Name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
