# Generated by Django 2.2.4 on 2020-02-08 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0013_auto_20200208_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerquiz',
            name='answer',
        ),
    ]
