# Generated by Django 2.2.4 on 2020-02-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0014_remove_careerquiz_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerquiz',
            name='choice_four',
            field=models.CharField(default='Easy', max_length=200),
        ),
        migrations.AlterField(
            model_name='careerquiz',
            name='choice_one',
            field=models.CharField(default='Difficult', max_length=200),
        ),
        migrations.AlterField(
            model_name='careerquiz',
            name='choice_three',
            field=models.CharField(default='Neutral', max_length=200),
        ),
        migrations.AlterField(
            model_name='careerquiz',
            name='choice_two',
            field=models.CharField(default='Less Difficult', max_length=200),
        ),
        migrations.AlterField(
            model_name='careerquiz',
            name='qtype',
            field=models.CharField(default='Null', max_length=300),
        ),
    ]
