# Generated by Django 2.2.4 on 2020-01-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0002_clg_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='abroad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clg_name', models.CharField(max_length=200)),
                ('clg_loc', models.CharField(max_length=200)),
                ('clg_website', models.CharField(max_length=300)),
                ('clg_phno', models.CharField(max_length=10)),
            ],
        ),
    ]
