# Generated by Django 2.2.4 on 2020-01-08 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0003_abroad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abroad',
            name='clg_phno',
        ),
        migrations.RemoveField(
            model_name='clg',
            name='clg_city',
        ),
        migrations.RemoveField(
            model_name='clg',
            name='clg_country',
        ),
        migrations.RemoveField(
            model_name='clg',
            name='clg_phno',
        ),
        migrations.RemoveField(
            model_name='clg',
            name='image',
        ),
    ]
