# Generated by Django 2.2.4 on 2020-01-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0004_auto_20200108_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='abroad',
            name='clg_top_field',
            field=models.TextField(default='law'),
        ),
    ]
