# Generated by Django 2.2.4 on 2020-01-16 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0005_abroad_clg_top_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='abroad',
        ),
    ]
