# Generated by Django 2.2.4 on 2020-01-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image1',
            field=models.ImageField(default='default.jpg', upload_to='blog_pics'),
        ),
    ]
