# Generated by Django 2.2.4 on 2020-01-24 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image1',
        ),
    ]
