# Generated by Django 2.2.4 on 2020-02-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='text',
        ),
    ]
