# Generated by Django 2.2.5 on 2020-01-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Review_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sentiments',
            field=models.CharField(default='neutral', max_length=15),
        ),
    ]
