# Generated by Django 2.2.4 on 2020-02-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Review_mgmt', '0002_review_sentiments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='sentiments',
        ),
    ]
