# Generated by Django 2.2.4 on 2020-01-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='law', max_length=200)),
                ('Summary', models.TextField()),
                ('Career_Opportunities', models.TextField()),
                ('How_to_become', models.TextField()),
                ('Important_Facts', models.TextField()),
                ('Work_Description', models.TextField()),
                ('Pros_and_Cons', models.TextField()),
            ],
        ),
    ]
