# Generated by Django 2.2.4 on 2019-12-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='text3',
            field=models.TextField(default='null'),
        ),
    ]
