# Generated by Django 2.2.4 on 2019-12-21 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_intro_text3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intro',
            name='text3',
        ),
    ]
