# Generated by Django 2.2.4 on 2019-12-23 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_remove_intro_text3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='intro',
        ),
    ]
