# Generated by Django 2.2.4 on 2020-02-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.CharField(max_length=200)),
                ('op1', models.CharField(max_length=3)),
                ('op2', models.CharField(max_length=3)),
            ],
        ),
    ]
